import theme from '@/theme';
import { CssBaseline, ThemeProvider, Typography } from '@mui/material';
import Box from '@mui/material/Box'
import type { Metadata } from 'next';
import { Montserrat, Inter } from 'next/font/google';

console.log({theme});

const montserrat = Montserrat({
  subsets: ['cyrillic', 'latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-montserrat',
});

const inter = Inter({
  subsets: ['cyrillic', 'latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider theme={theme}>
      <CssBaseline />

      <html
        lang='en'
        className={montserrat.className + ' ' + inter.className}
      >
        <body>
          <Box component='header'><Typography variant='category'>Header</Typography></Box>

          <Box component='main'>{children}</Box>

          <Box component='footer'>Footer</Box>
        </body>
      </html>
    </ThemeProvider>
  );
}
